---
name: Bug Fix Pull Request
description: Submit a pull request for fixing a bug
title: "[BUGFIX] "
labels: ["bugfix", "triage"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug fix.
      placeholder: Describe the bug that was fixed and how this PR addresses it.
    validations:
      required: true

  - type: input
    id: issue-url
    attributes:
      label: Related Issue URL
      description: Link to the GitHub issue this PR fixes
      placeholder: https://github.com/muhammad-fiaz/logly/issues/ISSUE_NUMBER
    validations:
      required: true

  - type: textarea
    id: root-cause
    attributes:
      label: Root Cause
      description: What was the root cause of the bug?
      placeholder: Explain what caused the bug and why it occurred.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: How was the bug fixed?
      placeholder: Describe the technical solution and implementation details.
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: How was this fix tested?
      placeholder: |
        - Unit tests added/updated
        - Integration tests
        - Manual testing steps
        - Test results
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Logly Version
      description: What version of Logly was this tested against?
      placeholder: e.g., 0.1.4
    validations:
      required: true

  - type: checkboxes
    id: code-quality
    attributes:
      label: Code Quality Checklist
      description: Please confirm the following
      options:
        - label: "cargo fmt has been run"
          required: true
        - label: "mypy passes with no errors"
          required: true
        - label: "pylint and clippy pass with no warnings"
          required: true
        - label: "cargo test and pytest pass"
          required: true
        - label: "uv run ruff format has been applied"
          required: true
        - label: "All new functions/classes have docstrings"
          required: true
        - label: "No unnecessary changes included"
          required: true

  - type: checkboxes
    id: ai-usage
    attributes:
      label: AI Usage Disclosure
      description: Please disclose AI tool usage
      options:
        - label: "I have used AI tools (GitHub Copilot, ChatGPT, etc.) to assist with this implementation"
        - label: "No AI tools were used in this implementation"
      validations:
        required: true

  - type: textarea
    id: reviewers
    attributes:
      label: Reviewers
      description: "@mention the person or team responsible for reviewing this PR"
      placeholder: "@reviewer1 @reviewer2"
    validations:
      required: true

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes (if any)
      description: Does this fix introduce any breaking changes?
      placeholder: |
        If yes, describe them and provide migration guidance:
        - Breaking change 1
        - Migration steps...

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional information or context reviewers should be aware of.
      placeholder: |
        - Performance impact
        - Security considerations
        - Future improvements
        - Related PRs