---
name: Documentation Pull Request
description: Submit a pull request for documentation updates
title: "[DOCS] "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is being updated?
      options:
        - API Reference
        - Quick Start Guide
        - User Guide
        - Examples/Cookbook
        - README
        - Code Comments/Docstrings
        - Changelog
        - Other
    validations:
      required: true

  - type: input
    id: doc-location
    attributes:
      label: Documentation Location
      description: Where is the documentation located?
      placeholder: e.g., docs/api-reference/logging.md, README.md, examples/basic-console.md
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Changes Made
      description: What documentation changes were made?
      placeholder: |
        - What was added, updated, or corrected?
        - What sections were affected?
        - What examples were added or modified?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Changes
      description: Why was this documentation update needed?
      placeholder: |
        - What was unclear, incorrect, or missing?
        - What user feedback prompted this change?
        - What new features need documentation?
        - What bugs were documented?
    validations:
      required: true

  - type: input
    id: issue-url
    attributes:
      label: Related Issue URL (if applicable)
      description: Link to any related GitHub issue
      placeholder: https://github.com/muhammad-fiaz/logly/issues/ISSUE_NUMBER

  - type: textarea
    id: validation
    attributes:
      label: Validation
      description: How was the documentation validated?
      placeholder: |
        - Documentation builds successfully (mkdocs build)
        - Links are working
        - Examples are correct and runnable
        - Screenshots/images are updated
        - Cross-references are accurate
    validations:
      required: true

  - type: checkboxes
    id: doc-checklist
    attributes:
      label: Documentation Checklist
      description: Please confirm the following
      options:
        - label: "Documentation builds without warnings or errors"
          required: true
        - label: "All links are working and accurate"
          required: true
        - label: "Code examples are correct and runnable"
          required: true
        - label: "Screenshots/images are updated if needed"
          required: true
        - label: "Table of contents and navigation are correct"
          required: true
        - label: "Spelling and grammar are correct"
          required: true

  - type: checkboxes
    id: code-quality
    attributes:
      label: Code Quality Checklist (if code changes included)
      description: If this PR includes code changes, please confirm
      options:
        - label: "cargo fmt has been run"
        - label: "mypy passes with no errors"
        - label: "pylint and clippy pass with no warnings"
        - label: "cargo test and pytest pass"
        - label: "uv run ruff format has been applied"
        - label: "All new functions/classes have docstrings"
        - label: "No unnecessary changes included"

  - type: checkboxes
    id: ai-usage
    attributes:
      label: AI Usage Disclosure
      description: Please disclose AI tool usage
      options:
        - label: "I have used AI tools (GitHub Copilot, ChatGPT, etc.) to assist with this implementation"
        - label: "No AI tools were used in this implementation"
      validations:
        required: true

  - type: textarea
    id: reviewers
    attributes:
      label: Reviewers
      description: "@mention the person or team responsible for reviewing this PR"
      placeholder: "@reviewer1 @reviewer2"
    validations:
      required: true

  - type: textarea
    id: preview
    attributes:
      label: Documentation Preview
      description: If applicable, provide links to preview the documentation changes.
      placeholder: |
        - Local build URL
        - Netlify/GitHub Pages preview
        - Screenshots of changes

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional information or context reviewers should be aware of.
      placeholder: |
        - Impact on user experience
        - Related documentation updates needed
        - Translation requirements
        - Accessibility considerations