---
name: Help/Support Pull Request
description: Request help or support with a pull request
title: "[HELP] "
labels: ["help", "triage"]
assignees: []
body:
  - type: textarea
    id: help-request
    attributes:
      label: Help Request
      description: What help do you need with this pull request?
      placeholder: Describe what you're struggling with or what help you need.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about your help request.
      placeholder: |
        - What are you trying to accomplish?
        - What have you tried so far?
        - What documentation have you read?
        - What errors are you encountering?
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: What's the current state of your changes?
      placeholder: |
        - What code have you written?
        - What tests are passing/failing?
        - What documentation exists?
        - What is working vs. not working?
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Provide relevant code snippets that demonstrate your issue.
      placeholder: |
        ```python
        # Your code here
        ```
      render: python
    validations:
      required: false

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: If applicable, provide error messages or stack traces.
      placeholder: |
        ```
        # Error output here
        ```
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Logly Version
      description: What version of Logly are you working with?
      placeholder: e.g., 0.1.4
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: Branch Name
      description: What branch are you working on?
      placeholder: e.g., feature/new-logging-level
    validations:
      required: true

  - type: dropdown
    id: help-type
    attributes:
      label: Type of Help Needed
      description: What type of help do you need?
      options:
        - Code Review
        - Implementation Guidance
        - Testing Help
        - Documentation Help
        - Build/Setup Issues
        - Performance Issues
        - Bug Debugging
        - API Design
        - Other
    validations:
      required: true

  - type: checkboxes
    id: attempted-solutions
    attributes:
      label: What Have You Tried?
      description: Please confirm what troubleshooting steps you've attempted
      options:
        - label: "Checked existing documentation"
        - label: "Searched for similar issues/PRs"
        - label: "Ran tests locally"
        - label: "Checked code formatting (cargo fmt, ruff)"
        - label: "Verified type hints (mypy)"
        - label: "Ran linting (pylint, clippy)"
        - label: "Tested on different environments"
        - label: "Asked in community discussions"

  - type: checkboxes
    id: ai-usage
    attributes:
      label: AI Usage Disclosure
      description: Please disclose AI tool usage
      options:
        - label: "I have used AI tools (GitHub Copilot, ChatGPT, etc.) to assist with this implementation"
        - label: "No AI tools were used in this implementation"
      validations:
        required: true

  - type: textarea
    id: reviewers
    attributes:
      label: Potential Reviewers
      description: "@mention people who might be able to help"
      placeholder: "@reviewer1 @reviewer2"
    validations:
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: Timeline/Urgency
      description: Is there a timeline or urgency for this help request?
      placeholder: |
        - When do you need this resolved?
        - Is this blocking other work?
        - Any deadlines?

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional information or context.
      placeholder: |
        - Related issues or PRs
        - Your experience level
        - Specific constraints
        - Alternative approaches considered